version: "3.7"
services:
  api:
    build: todo-api
    environment:
      NODE_ENV: test
      LOG_LEVEL: silent
      PGPORT: 5432
      PGHOST: postgres
      PGUSER: todo
      PGDATABASE: todo
      PGPASSWORD: test
      REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_SESSION_DB: 0
      SESSION_TIMEOUT: 900
      JWT_SECRET: test
      SESSION_SECRET: test
    depends_on:
      - ddl
      - redis
  postgres:
    build: todo-db
    environment:
      PGPASSWORD: test
      POSTGRES_PASSWORD: test
  ddl:
    build: todo-ddl
    command: deploy
    environment:
      PGPORT: 5432
      PGHOST: postgres
      PGPASSWORD: test
      PGUSER: todo
      PGDATABASE: todo
    depends_on:
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
