version: "3.7"
services:
  lib-amqp-wrapper:
    image: amqp-wrapper:latest
  lib-auth-helper:
    image: auth-helper:latest
  lib-healthier:
    image: healthier:latest
  todo-items:
    image: todo-items:latest
    command: node index.js
    environment:
      LOG_LEVEL: debug
      NODE_ENV: production
      AMQP_VHOST: todo
      AMQP_HOST: rabbitmq
      PGHOST: postgres
      PGUSER: todo
      PGDATABASE: todo
      HEALTH_CHECK_PORT_ITEMS: 49999
    secrets:
      - PGPASSWORD
      - AMQP_USER
      - AMQP_PASS
      - JWT_SECRET
    depends_on:
      - lib-amqp-wrapper
      - lib-auth-helper
      - rabbitmq
      - postgres
  todo-auth:
    image: todo-auth:latest
    command: node index.js
    environment:
      LOG_LEVEL: debug
      NODE_ENV: production
      AMQP_VHOST: todo
      AMQP_HOST: rabbitmq
      PGHOST: postgres
      PGUSER: todo
      PGDATABASE: todo
      HEALTH_CHECK_PORT_AUTH: 49999
    secrets:
      - PGPASSWORD
      - AMQP_USER
      - AMQP_PASS
    depends_on:
      - lib-amqp-wrapper
      - rabbitmq
      - postgres
  todo-localization:
    image: todo-localization:latest
    command: node index.js
    environment:
      LOG_LEVEL: debug
      NODE_ENV: production
      AMQP_VHOST: todo
      AMQP_HOST: rabbitmq
      PGHOST: postgres
      PGUSER: todo
      PGDATABASE: todo
      HEALTH_CHECK_PORT_I18N: 49999
    secrets:
      - PGPASSWORD
      - AMQP_USER
      - AMQP_PASS
    depends_on:
      - lib-amqp-wrapper
      - rabbitmq
      - postgres
  todo-api:
    image: todo-api:latest
    command: node index.js
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      AMQP_VHOST: todo
      AMQP_HOST: rabbitmq
      PGHOST: postgres
      PGUSER: todo
      PGDATABASE: todo
      REDIS_HOST: redis
      REDIS_SESSION_DB: 0
      SESSION_TIMEOUT: 900
      HEALTH_CHECK_PORT_API: 49999
    secrets:
      - PGPASSWORD
      - SESSION_SECRET
      - AMQP_USER
      - AMQP_PASS
      - JWT_SECRET
    depends_on:
      - lib-amqp-wrapper
      - lib-auth-helper
      - todo-auth
      - todo-localization
      - todo-items
      - redis
  nginx:
    image: todo-lb:latest
    ports:
      - "3000:80"
    depends_on:
      - todo-api
    healthcheck:
      test: ["CMD-SHELL", "nc localhost 80 < /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: todo-db:latest
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      PGPASSWORD_FILE: /var/run/secrets/PGPASSWORD_FILE
      POSTGRES_PASSWORD_FILE: /var/run/secrets/POSTGRES_PASSWORD
    expose:
      - "5432"
    secrets:
      - PGPASSWORD
      - POSTGRES_PASSWORD
  ddl:
    image: todo-ddl:latest
    command: deploy --verify
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: todo
      PGDATABASE: todo
      PGPORT: "5432"
    secrets:
      - PGPASSWORD
  redis:
    image: redis:latest
    volumes:
      - "redis_data:/data"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "if [ $$(redis-cli ping) = 'PONG' ]; then exit 0; fi; exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    sysctls:
      - net.core.somaxconn=511
  rabbitmq:
    image: rabbitmq:management-alpine
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "15671"
      - "15672"
      - "25672"
    volumes:
      - "rabbit_data:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_VHOST: todo
      RABBITMQ_DEFAULT_USER_FILE: /var/run/secrets/AMQP_USER
      RABBITMQ_DEFAULT_PASS_FILE: /var/run/secrets/AMQP_PASS
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl node_health_check"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - AMQP_USER
      - AMQP_PASS
volumes:
  pg_data:
  redis_data:
  rabbit_data:
secrets:
  JWT_SECRET:
    file: .env/JWT_SECRET
  SESSION_SECRET:
    file: .env/SESSION_SECRET
  PGPASSWORD:
    file: .env/PGPASSWORD
  POSTGRES_PASSWORD:
    file: .env/POSTGRES_PASSWORD
  AMQP_USER:
    file: .env/AMQP_USER
  AMQP_PASS:
    file: .env/AMQP_PASS
